import re

# Pattern for captions likely discussing quantum circuits 
POSITIVE_PATTERN = re.compile(
    r"\b(quantum circuits?|gates?|"
    r"implementing|"
    r"implementation"
    r")\b",
    flags=re.IGNORECASE
)




# Pattern for quantum gate symbols. This Regex pattern is generated by ChatGPT based on a comprehensive list of common quantum gates and their variations.
QUANTUM_GATES_PATTERN = re.compile(
    r"""
    (?<!\w)  # no letter/number before
    (
        # ---- Single-qubit gates ----
        H|Hadamard|
        X|Pauli[- ]?X|
        Y|Pauli[- ]?Y|
        Z|Pauli[- ]?Z|
        T|T\s*gate|
        S|S\s*gate|
        ID|Identity|
        SWAP|Swap\s*gate|

        # ---- Multi-qubit / controlled gates ----
        CNOT|Controlled[- ]?NOT|
        CZ|Controlled[- ]?Z|
        CCX|Toffoli|Toffoli\s*gate|

        # ---- Parameterized gates (RX, RY, RZ, U1-U3) with optional Greek letters ----
        C?[α-ωA-Za-z]*R[XYZ]\s*\([^)]+\)|   # e.g., RX(θ), RφZ(θ)
        U[123]\s*\([^)]+\)|                  # e.g., U1(θ), U3(θ,φ,λ)

        # ---- Tensor products ----
        (?:H|X|Y|Z|T|S|ID|SWAP|RX|RY|RZ|U[123]|CNOT|CZ|CCX|Toffoli)\s*
        (?:⊗\s*(?:H|X|Y|Z|T|S|ID|SWAP|RX|RY|RZ|U[123]|CNOT|CZ|CCX|Toffoli)\s*)+

        # ---- Indexed gates (subscripts / numbers) ----
        (?:H|X|Y|Z|T|S|ID|SWAP|CNOT|CZ|CCX|Toffoli|RX|RY|RZ|U[123])[_\d]+
    )
    (?!\w)  # no letter/number after
    """,
    flags=re.IGNORECASE | re.VERBOSE
)




# Pattern for words to exclude
NEGATIVE_PATTERN = re.compile(
    r"\b(graphs?|tables?|equations?|plots?|comparisons?|benchmarks?|vs|trends?|histograms?|charts?|probability distributions?|fidelity|infidelity|photons?|schematics?|simulations?|spectras?|populations?|errors?)\b",
    flags=re.IGNORECASE
)



# Pattern for captions likely discussing quantum algorithms and problems. This Regex pattern is generated by ChatGPT based on a comprehensive list of common quantum algorithms and problems.
QUANTUM_ALGO_PROBLEM_PATTERN = re.compile(
    r"""
    (?<!\w)  # no letter/number before
    (
        # ---------------- Core / Foundational Algorithms ----------------
        Grover(\s*search)?|
        Shor(\s*algorithm)?|
        Deutsch[-\s]?Jozsa|
        Bernstein[-\s]?Vazirani|
        Quantum\s+Fourier\s+Transform|QFT|
        HHL|Harrow[-\s]?Hassidim[-\s]?Lloyd|
        Quantum\s+Phase\s+Estimation|QPE|

        # ---------------- Variational / Hybrid Algorithms ----------------
        Variational\s+Quantum\s+Eigensolver|VQE|
        Quantum\s+Approximate\s+Optimization\s+Algorithm|QAOA|
        Variational\s+Hamiltonian\s+Solver|VHS|
        Quantum\s+Simulated\s+Annealing|
        Quantum\s+Machine\s+Learning|QML|

        # ---------------- Quantum Simulation / Chemistry ----------------
        Hamiltonian\s+Simulation|
        Ground\s+state\s+energy|
        Quantum\s+State\s+Preparation|
        Quantum\s+Optimization|
        Quantum\s+Sampling|
        Quantum\s+Chemistry|
        Quantum\s+Control|
        Quantum\s+Measurement|

        # ---------------- Error Correction / Fault-Tolerance ----------------
        Quantum\s+Error\s+Correction|QEC|
        Surface\s+Code|
        Decoherence|
        Error\s+Mitigation|
        Fault[-\s]?Tolerant|
        Fault[-\s]?Tolerance|
        Entanglement\s+Generation|
        Noise\s+Resilience|
        Logical\s+Qubit

        # ---------------- Abbreviations ----------------
        |VQE|QAOA|QPE|QFT|QEC|QML|HHL
    )
    (?!\w)  # no letter/number after
    """,
    flags=re.IGNORECASE | re.VERBOSE
)




ABBREVIATION_MAPPING = {
    "VQE": "Variational Quantum Eigensolver",
    "QAOA": "Quantum Approximate Optimization Algorithm",
    "QPE": "Quantum Phase Estimation",
    "QFT": "Quantum Fourier Transform",
    "QEC": "Quantum Error Correction",
    "QML": "Quantum Machine Learning",
    "HHL": "Harrow-Hassidim-Lloyd",
    "VHS": "Variational Hamiltonian Solver"
}




GATE_NORMALIZATION_MAP = {
    # Single-qubit
    "HADAMARD": "H",
    "PAULI-X": "X",
    "PAULI X": "X",
    "X": "X",
    "PAULI-Y": "Y",
    "PAULI Y": "Y",
    "Y": "Y",
    "PAULI-Z": "Z",
    "PAULI Z": "Z",
    "Z": "Z",
    "T GATE": "T",
    "T": "T",
    "S GATE": "S",
    "S": "S",
    "IDENTITY": "ID",
    "ID": "ID",

    # Two / multi-qubit
    "SWAP": "SWAP",
    "SWAP GATE": "SWAP",
    "CNOT": "CNOT",
    "CONTROLLED-NOT": "CNOT",
    "CONTROLLED NOT": "CNOT",
    "CZ": "CZ",
    "CONTROLLED-Z": "CZ",
    "CONTROLLED Z": "CZ",
    "CONTROLLED X": "CX",
    "CCX": "CCX",
    "TOFFOLI": "CCX",
    "TOFFOLI GATE": "CCX",
}




CAPTION_REGEX = re.compile(
    r'^\s*(Figure|Fig\.?|FIGURE)\s*(\d+)(\s*[:\.\-]|\s+\(|$)', re.IGNORECASE
)

